project:
  type: book

book:
  title: "Lorem Ipsum Dolor Sit Amet Consectetur Adipiscing Elit Sed Do Eiusmod Tempor"
  author:
    - name: Jane A. Smith
  chapters:
    - index.qmd
    - chapters/chapter-2.qmd
    - chapters/chapter-3.qmd
    - chapters/chapter-4.qmd
  appendices:
    - chapters/appendix-a.qmd
    - chapters/appendix-b.qmd

bibliography: sample-references.bib

department: Lorem Ipsum
degree: Doctor of Philosophy
department-prefix: "Department of"
submission-month: June
submission-year: "2026"
abstract: |
  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
acknowledgments: |
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.
dedication: |
  *Lorem ipsum dolor sit amet.*
show-toc: true
show-lof: true
show-lot: true

format:
  stanford-thesis-typst: default
